people/urls.py
#
# Copyright 2017, MIT TESS
#
# tess-tev is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# tess-tev is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with tess-tev.  If not, see <http://www.gnu.org/licenses/>.
#

from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from django.contrib.auth.views import *

from .views import *
from .forms import PasswordForm

def url_tree(regex, *urls):
    return url(regex, include(urls))

UIDB = r'^pwd/(?P<uidb64>[0-9A-Za-z_\-]+?)/(?P<token>.+)/$'


urlpatterns = [
  url(r'^login/',     login, name='login'),
  url(r'^logout/',    logout, name='logout'),

  url(r'^pwd/$',      password_reset, {'password_reset_form': PasswordForm, 'post_reset_redirect': 'people:password_reset_done' }, name='password_reset'),
  url(UIDB,           password_reset_confirm,  name='password_reset_confirm'),
  url(r'^pwd/done/$', password_reset_complete, name='password_reset_complete'),
  url(r'^pwd/sent/$', password_reset_done,     name='password_reset_done'),

  url(r'^$',                     MyProfile.as_view(),   name='my_profile'),
  url(r'^edit/$',                EditProfile.as_view(), name='edit_profile'),
  url(r'^~(?P<username>[^\/]+)', UserDetail.as_view(),  name='view_profile'),
]

tevsite/urls.py
#
# Copyright 2014, Martin Owens
#           2017, MIT TESS
#
# tess-tev is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# tess-tev is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with tess-tev.  If not, see <http://www.gnu.org/licenses/>.
#
# Code imported from inkscape-web 2017-10-18 AGPLv3
#

from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from .views import *
from vetting.views import DashboardView

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('people.urls', namespace='people')),
    url(r'^v/', include('vetting.urls', namespace='vet')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


for e in ('403','404','500'):
    locals()['handler'+e] = Error.as_error(e)
    urlpatterns.append(url('^error/%s/$' % e, Error.as_error(e)))

tevsite/views.py
#
# Copyright 2014, Martin Owens
#           2017, MIT TESS
#
# tess-tev is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# tess-tev is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with tess-tev.  If not, see <http://www.gnu.org/licenses/>.
#
# Code imported from inkscape-web 2017-10-18 AGPLv3
#

__all__ = ('Error',)

from django.conf import settings
from django.views.generic import TemplateView, FormView, ListView


class Error(TemplateView):
    @classmethod
    def as_error(cls, status):
        view = cls.as_view(template_name='error/%s.html' % status)
        def _inner(request):
            response = view(request, status=int(status))
            if hasattr(response, 'render'):
                response.render()
            return response
        return _inner

    def post(self, request, **kw):
        return self.get(request, **kw)

    def get(self, request, **kw):
        context = self.get_context_data(**kw)
        if not settings.DEBUG or kw['status'] != 404:
            try:
                path = request.get_full_path()
                ErrorLog.objects.get_or_create(uri=path, **kw)[0].add()
            except:
                pass
        return self.render_to_response(context, **kw)

tevsite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="TESS Exoplanet Vetter">
    <meta name="author" content="Martin Owens">

    <link rel="shortcut icon" href="{% static "images/icon.svg" %}"/>
    <title>{% block "title" %}{{ title|default:"Page" }} - TEV{% endblock %}</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-dialog.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/basic.css' %}" rel="stylesheet">

    {% block extra_css %}
    {% endblock %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/basic.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block extra_js %}
    {% endblock %}

    {{ form.media }}
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}" style="padding: 2px;"><img style="width: 47px;" src="{% static "images/logo.svg" %}"/></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    {% include "nav.html" %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    {% block "body" %}
    <!-- Page Content -->
    <div class="container">
      {% if breadcrumbs and breadcrumbs|length > 1 %}
        <ul class="breadcrumb">
          {% for link, name in breadcrumbs %}
            {% if not forloop.last %}
	      <li><a href="{{ link }}">{{ name }}</a></li>
            {% else %}
              <li class="active">{{ name }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      {% endif %}

        {% block content %}
            (main_content)
        {% endblock %}

        {% block footer_content %}
            <!-- Footer -->
            <hr/>
            <footer style="margin-bottom: 30px;">
              <div class="row">
                <div class="col-lg-12">
                  <center>
                    &copy; {% now "Y" %} MIT / TESS - AGPLv3
                    &nbsp;|&nbsp; <a href="mailto:{{ admin_email }}">Contact</a><br>
                  </center>

                </div>
              </div>
            </footer>
        {% endblock %}
    </div>
    {% endblock %}

    {% block extra_footer_js %}
    {% endblock %}
</body>
</html>

tevsite/templates/bootstrap_radio.html
{% with id=widget.attrs.id %}<div{% if id %} id="{{ id }}"{% endif %}{% if widget.attrs.class %} class="{{ widget.attrs.class }}"{% endif %}>{% for group, options, index in widget.optgroups %}{% for option in options %}{% if option.value %}
  <div class="radio">{% include option.template_name with widget=option %}</div>{% endif %}{% endfor %}{% endfor %}</div>{% endwith %}

tevsite/templates/fields.html
{% load i18n static formextra %}

{% for field in fieldset %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    {% if field.errors %}
      <span class="text-danger">
        {% for error in field.errors %}
          <br />{{ field.label_tag }} {{ error }}
        {% endfor %}
      </span>
    {% else %}
      {{ field.label_tag }}
    {% endif %}
    {% if forloop.first %}
      {{ field|placeholder:field.label|formfield|autofocus }}
    {% else %}
      {{ field|placeholder:field.label|formfield }}
    {% endif %}
    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

tevsite/templates/modal.html
{% extends "base.html" %}
{% load i18n static %}

{% block content %}
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        {% block "dialog-title" %}<h4 class="modal-title">{% block "title" %}{{ title|default:"Dialog Title" }}{% endblock %}</h4>{% endblock %}
        {% block "dialog-subtitle" %}{% endblock %}
      </div>
        {% if form.non_field_errors %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">{{ error }}</div>
          {% endfor %}
        {% endif %}
      <div class="modal-body">
        {% block "dialog-body" %}{% endblock %}
        {% if form or formset or delete %}
          {% block "dialog-form" %}
            <form method="POST" action="{% block "dialog-action" %}{% endblock %}"
                 {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
              {% csrf_token %}

              <input type="hidden" name="msie11bug" value="http://stackoverflow.com/questions/20149751/ie11-only-submit-bug" />

              {% if next or request.GET.next %}
                <input type="hidden" name="next" value="{{ next|default:request.GET.next }}" />
              {% endif %}

              {% if form.fieldsets %}
                <div class="tabs">
                  {% for label, fieldset in form.fieldsets %}
                    <label class="tab" for="tab{{ forloop.counter }}">{{ label }}</label>
                  {% endfor %}
                </div>
                {% for label, fieldset in form.fieldsets %}
                  <div class="fields" id="tab{{ forloop.counter }}">
                    {% include "fields.html" %}
                  </div>
                {% endfor %}
              {% else %}
                {% with form as fieldset %}
                  {% include "fields.html" %}
                {% endwith %}
              {% endif %}

              <div class="modal-footer">
                {% block "form-buttons" %}
                  <button type="submit" class="btn btn-primary">Go</button>
                {% endblock %}
              </div>
            </form>
          {% endblock %}
        {% else %}
          <div class="modal-footer">{% block "dialog-buttons" %}{% endblock %}
          </div>
        {% endif %}
        </div>
      </div>
  </div>
{% endblock %}

tevsite/templates/nav.html
    <li>
      <a href="/">Home</a>
    </li>

    {% if not request.user.is_authenticated %}
        <li>
            <a href="{@ url 'users:signup' %}">Sign Up</a>
        </li>
        <li>
        <a href="{% url 'people:login' %}">Log In</a>
        </li>
    {% else %}
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ request.user.get_name }} <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><a href="{% url 'people:edit_profile' %}"><span class="glyphicon glyphicon-user"></span> Edit Profile</a></li>
          {% if request.user.is_staff %}
            <li><a href="{% url 'admin:index' %}"><span class="glyphicon glyphicon-cog"></span> Admin</a></li>
          {% endif %}
          <li><a href="{% url 'people:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
        </ul>
      </li>
    {% endif %}

    {% if request.user.get_role %}
      <li>
        <a>{{ request.user.get_role }}</a>
      </li>
    {% endif %}